version: '3.8'

services:
  api:
    container_name: json_to_word_backend
    build:
      context: ./backend      
      dockerfile: Dockerfile
    ports:
      - "443:8443"            
    volumes:
      - ./certs:/etc/ssl/certs_app
    command: >
      uvicorn main:app 
      --host 0.0.0.0 
      --port 8443 
      --ssl-keyfile /etc/ssl/certs_app/localhost+1-key.pem 
      --ssl-certfile /etc/ssl/certs_app/localhost+1.pem